let age = prompt('Привет! Сколько тебе лет?', 10);
let headText = "Попробуй еще раз, только на этот раз укажи возраст цифрами";
if (age <= 20) {  // Тебе меньше 20 лет!;
    headText = "Еще совсем зеленый!";
    alert(`Тебе ${age}!`);
} else if (age <= 50) {  // Тебе в интервале от 20 до 50 лет!; 
    headText = "В самом расцвете сил!";
    alert(`Тебе ${age}!`);
} else {  // Тебе больше 50 лет!;
    headText = "Пора привыкать к земле!";
    alert(`Тебе ${age}!`);
};
document.getElementById("ages").innerHTML = headText;
