let age = prompt('Привет! Сколько тебе лет?', 10);
let headText = "Попробуй еще раз, только на этот раз укажи возраст цифрами";
if (age <= 20) {  // Тебе меньше 20 лет!;
    headText = `Тебе ${age}! <br>Еще совсем зеленый!`;
} else if (age <= 50) {  // Тебе в интервале от 20 до 50 лет!; 
    headText = `Тебе ${age}! <br>В самом расцвете сил!`;
} else {  // Тебе больше 50 лет!;
    headText = `Тебе ${age}! <br>Пора привыкать к земле!`;
};
document.getElementById("ages").innerHTML = headText;
